steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - docker pull ${_REGISTRY}/$PROJECT_ID/${_ENV}/${_IMAGE}:latest || exit 0
    id: 'cache warm-up'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_REGISTRY}/$PROJECT_ID/${_ENV}/${_IMAGE}:$SHORT_SHA
      - -t
      - ${_REGISTRY}/$PROJECT_ID/${_ENV}/${_IMAGE}:latest
      - --cache-from
      - ${_REGISTRY}/$PROJECT_ID/${_ENV}/${_IMAGE}:latest
      - .
    id: 'build'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - echo $SHORT_SHA > ${_IMAGE}
    id: 'prepare artifacts'
    waitFor:
      - '-'

substitutions:
 _IMAGE: ethereum-etl
 _REGISTRY: gcr.io
 _ENV: dev

images:
  - ${_REGISTRY}/$PROJECT_ID/${_ENV}/${_IMAGE}:$SHORT_SHA
  - ${_REGISTRY}/$PROJECT_ID/${_ENV}/${_IMAGE}:latest

artifacts:
  objects:
    location: gs://artifacts-${PROJECT_ID}/tags/${_ENV}/
    paths:
      - ${_IMAGE}

